### ISSUE TITLE
Encyclopydia missing

### ISSUE THREAD

**Issue by yangkl96** [searlelab/chronologer#2]
This is a small issue, but it is not clear how encyclopydia can be installed. I simply commented out the lines where it was required and it worked fine.

```
(chronologer_env) C:\Users\yangkl\Downloads\proteomics\predictionTools>python Train_Chronologer.py --lr_weight 0.5 --gpu --output_dir chronologer\models
Traceback (most recent call last):
  File "C:\Users\yangkl\Downloads\proteomics\predictionTools\Train_Chronologer.py", line 9, in <module>
    from chronologer.src.chronologer.training_functions import train_chronologer
  File "C:\Users\yangkl\Downloads\proteomics\predictionTools\chronologer\src\chronologer\training_functions.py", line 17, in <module>
    from chronologer.src.training_loop import train_model
  File "C:\Users\yangkl\Downloads\proteomics\predictionTools\chronologer\src\training_loop.py", line 10, in <module>
    from encyclopydia.src.utils import timer
ModuleNotFoundError: No module named 'encyclopydia'
```

**Comment by elaboy** [comment]
I got it running by swapping `encyclopydia` with `chronologer`
